# Generated by Django 5.1.1 on 2024-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
